project_id = "jteynnxrmnqutacsdvat"

[functions.send-employee-invitation]
verify_jwt = true

[functions.accept-invitation]
verify_jwt = false

[functions.create-employee]
verify_jwt = false

[functions.seed-test-employees]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
